### PR TITLE
- Adding support to load libraries (Once) and save time in the deploy…

### PR DESCRIPTION
**Pull request by jabrena**
…ment process

- The user will have to update only one file config.gradle.
Previously, the user had to touch 2 files: MANIFEST.MF & config.gradle
- No more hardcoded password in the gradle files
- Added gradle files to load in the brick some files
- Added a simplelogger.properties example
- Added new configuration

### CODE REVIEW

**Review by JakubVanek — APPROVED** [review]

**Comment by JakubVanek** [comment]
I have hopefully finished the refactoring. I have a new review point:
```gradle
jvmFlags += "-noverify "
jvmFlags += "-XX:TieredStopAtLevel=1 "
jvmFlags += "-Djava.security.egd=file:/dev/./urandom"
```
You have commented with these flags that they should increase performance. You can uncomment them now in `config.gradle` and try them live.

Regards,

Jakub

**Comment by JakubVanek** [comment]
Closes https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/594 (delivered; maybe except for the targetted AppCDS, but that can be handled later)
Closes https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/592 (delivered)
Closes https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/583 (delivered)
Closes https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/516 (superseded)
Related to https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/445 (with slf4j-simple a manual preloading may not be necessary anymore)
Closes https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/444 (delivered)
Related to https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/417 (speeds up startup)

**Comment by jabrena** [comment]
Hi @JakubVanek,

installing the libraries from the installer:

I saw this messages:

```
> Task :installJavaLibraries
Strict host key checking is off. It may be vulnerable to man-in-the-middle attacks.

ev3dev#12| --- Running command: "echo -e "maker" | sudo -S /home/robot/java/installer.sh javaLibs" ---
ev3dev#13|
ev3dev#13|##############################
ev3dev#13|# EV3Dev-lang-java Installer #
ev3dev#13|##############################
ev3dev#13|
ev3dev#13|Platform detected: ev3
ev3dev#13|
ev3dev#13|[sudo] password for robot: 2018-12-02 08:27:50 URL:https://jitpack.io/com/github/ev3dev-lang-java/ev3dev-lang-java/2.4.16/ev3dev-lang-java-2.4.16.jar [115531/115531] -> "/home/robot/java/libraries/ev3dev-lang-java-2.4.16.jar" [1]
ev3dev#13|2018-12-02 08:27:50 URL:https://jitpack.io/com/github/ev3dev-lang-java/lejos-commons/0.7.2/lejos-commons-0.7.2.jar [108826/108826] -> "/home/robot/java/libraries/lejos-commons-0.7.2.jar" [1]
ev3dev#13|2018-12-02 08:27:51 URL:http://central.maven.org/maven2/net/java/dev/jna/jna/4.5.2/jna-4.5.2.jar [1484022/1484022] -> "/home/robot/java/libraries/jna-4.5.2.jar" [1]
ev3dev#13|2018-12-02 08:27:51 URL:http://central.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar [41203/41203] -> "/home/robot/java/libraries/slf4j-api-1.7.25.jar" [1]
ev3dev#13|2018-12-02 08:27:51 URL:http://central.maven.org/maven2/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar [290339/290339] -> "/home/robot/java/libraries/logback-classic-1.2.3.jar" [1]
ev3dev#13|2018-12-02 08:27:51 URL:http://central.maven.org/maven2/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar [471901/471901] -> "/home/robot/java/libraries/logback-core-1.2.3.jar" [1]
ev3dev#13|2018-12-02 08:27:51 URL:http://central.maven.org/maven2/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.jar [15257/15257] -> "/home/robot/java/libraries/slf4j-simple-1.7.25.jar" [1]
ev3dev#13|FINISHED --2018-12-02 08:27:51--
ev3dev#13|Total wall clock time: 3.0s
ev3dev#13|Downloaded: 7 files, 2.4M in 0.9s (2.66 MB/s)
ev3dev#13|find: 'jar': No such file or directory
ev3dev#13|find: 'jar': No such file or directory
ev3dev#13|find: 'jar': No such file or directory
ev3dev#13|find: 'jar': No such file or directory
ev3dev#13|find: 'jar': No such file or directory
ev3dev#13|find: 'jar': No such file or directory
ev3dev#13|find: 'jar': No such file or directory
```

What is it?

```
ev3dev#13|find: 'jar': No such file or directory
ev3dev#13|find: 'jar': No such file or directory
ev3dev#13|find: 'jar': No such file or directory
ev3dev#13|find: 'jar': No such file or directory
ev3dev#13|find: 'jar': No such file or directory
ev3dev#13|find: 'jar': No such file or directory
ev3dev#13|find: 'jar': No such file or directory
```

What we do in this methods?

```
# Dump JRI & library class list
function do_java_dump() {
    mkdir -p "$JAVA_APPCDS_DIR"
    rm -f "$JAVA_APPCDS_FILE"
    ( cat "$CLASSLIST";
    find "$JAVA_LIBRARY_DIR" -type f -exec jar tf {} \; |
    egrep '^.*\.class$' |
    sed 's/\.class$//' ) |
    sort -h >"$JAVA_APPCDS_FILE"
}

function do_fixup_perms() {
    chown robot:robot -R /home/robot
}
```

**Comment by JakubVanek** [comment]
Hmmm, I have added the jar program but haven't added a jar symlink. It is for generating the class list for AppCDS.

**Comment by jabrena** [comment]
Verified all points & discussed

**Pull request merged**
