### PR TITLE
Refactor the gradle code to a plugin

### PR DESCRIPTION
**Pull request by JakubVanek**
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/632
https://github.com/ev3dev-lang-java/ev3dev-lang-java/issues/634

The configuration namespace is now changed - I moved the configuration to `ev3.pref`. Paths can be overriden via `ev3.paths`.

### CODE REVIEW

**Comment by JakubVanek** [comment]
Apparently it is a bad idea to reset the source branch to be on par with the destination one. I have compacted the history a bit.

**Comment by JakubVanek** [comment]
Tested somewhat advanced configuration:

```gradle
import java.nio.file.Paths

// Project configuration
brick.pref {

    // Main class //
    mainClass = "example.programming.HelloWorld"

    // Brick connection parameters //
    brickHost = "10.0.0.89"
    brickUser = "robot"
    brickPassword = "maker"

    // Library section //
    libOpenCV = false
    libRXTX = false
    libCustom += "file:///path/to/a.jar"

    // Commands preceding Java //
    useSudo = false
    useTime = true
    useBrickrun = false


    // Java flags //

    jvmFlags += "-Xms64m"
    jvmFlags += "-Xmx64m"

    //jvmFlags += "-Xlog:gc*=info:stderr"
    jvmFlags += "-XX:+UseSerialGC"
    //jvmFlags += "-XX:+UseParallelGC"
    //jvmFlags += "-XX:+UseG1GC"

    jvmFlags += "-Xshare:on"
    jvmFlags += "-noverify"
    //jvmFlags += "-Djava.security.egd=file:/dev/./urandom"
    //jvmFlags += "-Dcom.sun.management.jmxremote=true"
    //jvmFlags += "-Dcom.sun.management.jmxremote.port=7091"
    //jvmFlags += "-Dcom.sun.management.jmxremote.authenticate=false"
    //jvmFlags += "-Dcom.sun.management.jmxremote.ssl=false"

    // JAR behaviour //
    slimJar = true
    useEmbeddedPaths = false
}

brick.paths {
    wrapperDir = "/home/robot"
    libraryDir = "/home/robot/java/libraries"
    programDir = "/home/robot/java/programs"
    splashDir  = "/home/robot/java/splashes"
    opencvJar  = "/usr/share/java/opencv.jar"
    rxtxJar    = "/usr/share/java/RXTXcomm.jar"
}

brick.build {
    splashPath = { proj ->
        return Paths.get("/home/kuba/common_splash.txt")
    }

    templateWrapper = { proj ->
        return """#!/bin/sh
/bin/true
cat ${proj.ev3.brickSplashPath()}
exec ${proj.ev3.getJavaCommand(true)}
"""
    }

    uploads = { proj ->
        return [
            [Paths.get(proj.projectDir.getAbsolutePath(), "mysterious_data_file.bin"), "/home/robot/mysterious_data_file.bin", 0755],
        ]
    }
}
```

EDIT: updated with `brick` prefix; fixed the shebang-after-newline issue

**Comment by jabrena** [comment]
Notes:
The main variable should be brick, not ev3. (ev3, brickpi, pistorms)

ev3.paths should be hidden. It is the default configuration. Transparent configuration

ev3.upload the same idea

The user only should upgrade brick.pref

**Comment by JakubVanek** [comment]
* > The main variable should be brick, not ev3. (ev3, brickpi, pistorms)
  * Oki, that's right, I was thinking only about ev3.
* > ev3.paths should be hidden. It is the default configuration. Transparent configuration
  * It is hidden by default - it doesn't have to be specified at all. However if the user is clever enough, they can find that there exists a `brick.paths` block.
* > ev3.upload the same idea
  * If you mean `ev3.build`, that is also intended for more advanced users. I believe these options can all be useful.
    * `splashPath` allows the user to change the default `<projectDir>/gradle/splash.txt` splash path,
    * `templateWrapper` allows the user to customize the shell script wrapper,
    * `uploads` allows the user to add something to upload together with the program.
  * None of these is required, they are defaulted. I added them because with moving the functionality to a plugin, we lose a possibility to hack something directly into the build code, so this tries to compensate for it.
* > The user only should upgrade `brick.pref`
  * Yup, this was only an example of what is possible. The `config.gradle` in this PR can remain. In fact, the ultra-minimum config is the following, because the rest of the options have a sane default.
```gradle
brick.pref {
    mainClass = "example.opencv.HelloWorldCV"
    brickHost = "192.168.1.2"
}
```

**Comment by JakubVanek** [comment]
Now `ev3` probably is successfully changed to `brick`.

**Comment by JakubVanek** [comment]
Before we merge this PR, we maybe should release the plugin as a non- `SNAPSHOT` version.

**Comment by JakubVanek** [comment]
released as 1.5.2 as of now

**Pull request merged**
